<?php
/**
 * Файл класса StorageBehavior
 *
 * @copyright Copyright (c) 2018, Oleg Chulakov Studio
 * @link http://chulakov.com/
 */

namespace chulakov\filestorage\behaviors;

use yii\rbac\Item;
use yii\di\Instance;
use yii\base\Behavior;
use chulakov\filestorage\FileStorage;

/**
 * Class StorageBehavior
 * @package chulakov\filestorage\behaviors
 */
class StorageBehavior extends Behavior
{
    /**
     * Компонент для работы с хранилищем
     *
     * @var string
     */
    public $storageClass = 'fileStorage';
    /**
     * Класс компонента хранилища
     *
     * @var FileStorage
     */
    public $storageComponent;

    /**
     * @inheritdoc
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->storageComponent = Instance::ensure($this->storageClass);
    }

    /**
     * Возвращает абсолютный или относительный URL-адрес к файлу
     *
     * @param bool $isAbsolute
     * @param Item $role
     * @return string
     * @throws \yii\base\InvalidParamException
     * @throws \chulakov\filestorage\exceptions\NoAccessException
     */
    public function getUrl($isAbsolute = false, $role = null)
    {
        return $this->storageComponent->getFileUrl($this->owner, $isAbsolute, $role);
    }

    /**
     * Возвращает полный путь к файлу в файловой системе
     *
     * @param Item $role
     * @return string
     * @throws \yii\base\InvalidParamException
     * @throws \chulakov\filestorage\exceptions\NoAccessException
     * @throws \chulakov\filestorage\exceptions\NotFoundFileException
     */
    public function getPath($role)
    {
        return $this->storageComponent->getFilePath($this->owner, $role);
    }

    /**
     * Возвращает URL-адрес до директории нахождения файлов определенного типа
     *
     * @param bool $isAbsolute
     * @return string
     * @throws \yii\base\InvalidParamException
     */
    public function getUploadUrl($isAbsolute = false)
    {
        return $this->storageComponent->getUploadUrl($this->owner, $isAbsolute);
    }

    /**
     * Возвращает абсолютный путь к директории хранения файлов определенного типа
     *
     * @return string
     * @throws \yii\base\InvalidParamException
     */
    public function getUploadPath()
    {
        return $this->storageComponent->getUploadPath($this->owner);
    }
}